"""Read/write access to the Medallion layers (bronze/silver/gold).

One repository per schema. Repositories depend inward on :mod:`domain` (allowed;
the dependency rule in ``docs/standards/architecture.md`` §2 only forbids
``domain`` from importing infrastructure) and translate domain entities to/from
rows defined in :mod:`persistence.tables`.

The pure row-mapping helpers (:func:`flight_to_silver_row`,
:func:`alert_to_gold_row`) are separated out so they can be unit-tested without a
database. The repository methods themselves are exercised by the skippable
integration suite against a real Postgres.

Only the *contract* lives here — all bodies raise :class:`NotImplementedError`
for dev-runner to implement.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from datetime import datetime
from decimal import Decimal
from typing import Any
from uuid import UUID

from sqlalchemy import Connection, select
from sqlalchemy import func as sqlalchemy_func

from domain.models import Alert, Flight, Route
from persistence.tables import flight, flight_alert, raw_search_response

# ── Pure mapping helpers (no I/O; unit-tested) ─────────────────────────────────


def flight_to_silver_row(
    flight: Flight, *, execution_id: UUID, captured_at: datetime
) -> dict[str, Any]:
    """Project a domain :class:`~domain.models.Flight` onto a ``silver.flight`` row.

    Contract (fully specified by ``test/persistence/test_mappers.py``): return a
    dict keyed by the ``silver.flight`` column names (excluding the autogenerated
    ``id``), namely ``execution_id``, ``captured_at``, ``route_origin``,
    ``route_destination``, ``departure_date``, ``carrier``, ``flight_number``,
    ``departure_time``, ``price``, ``currency`` and ``flight_id``. ``flight_id``
    is taken from :attr:`Flight.flight_id`; ``price`` stays a :class:`Decimal`;
    route fields come from ``flight.route``.
    """
    return {
        "execution_id": execution_id,
        "captured_at": captured_at,
        "route_origin": flight.route.origin,
        "route_destination": flight.route.destination,
        "departure_date": flight.route.departure_date,
        "carrier": flight.carrier,
        "flight_number": flight.flight_number,
        "departure_time": flight.departure_time,
        "price": flight.price,
        "currency": flight.currency,
        "flight_id": flight.flight_id,
    }


def alert_to_gold_row(alert: Alert, *, execution_id: UUID) -> dict[str, Any]:
    """Project a domain :class:`~domain.models.Alert` onto a ``gold.flight_alert`` row.

    Contract (fully specified by ``test/persistence/test_mappers.py``): return a
    dict keyed by the ``gold.flight_alert`` column names (excluding the
    autogenerated ``id``), namely ``execution_id``, ``flight_id``, ``price``,
    ``currency`` and ``alerted_at``, taken directly from the :class:`Alert`.
    """
    return {
        "execution_id": execution_id,
        "flight_id": alert.flight_id,
        "price": alert.price,
        "currency": alert.currency,
        "alerted_at": alert.alerted_at,
    }


# ── Repositories ───────────────────────────────────────────────────────────────


class BronzeRepository:
    """Append-only writer for ``bronze.raw_search_response``."""

    def __init__(self, connection: Connection) -> None:
        self._conn = connection

    def save_raw_response(
        self,
        *,
        execution_id: UUID,
        route: Route,
        captured_at: datetime,
        success: bool,
        payload: Mapping[str, Any] | None,
        error_message: str | None = None,
    ) -> int:
        """Insert one raw search-response row and return its generated ``id``.

        Contract: persist the intercepted payload verbatim as JSONB. On a failed
        extraction (``success=False``) ``payload`` may be ``None`` and
        ``error_message`` describes the failure. This is the row that makes a run
        "bem-sucedida" per the Regra de Persistência / Validações in
        ``docs/domain/regras_negocio.md`` (bronze written == run succeeded).
        """
        result = self._conn.execute(
            raw_search_response.insert().values(
                execution_id=execution_id,
                route_origin=route.origin,
                route_destination=route.destination,
                departure_date=route.departure_date,
                captured_at=captured_at,
                success=success,
                payload=payload,
                error_message=error_message,
            )
        )
        return result.inserted_primary_key[0]


class SilverRepository:
    """Writer for normalized flights in ``silver.flight``."""

    def __init__(self, connection: Connection) -> None:
        self._conn = connection

    def save_flights(
        self,
        *,
        execution_id: UUID,
        captured_at: datetime,
        flights: Sequence[Flight],
    ) -> list[int]:
        """Insert normalized flights; return the list of generated ``id`` values.

        Contract: one row per flight via :func:`flight_to_silver_row`, preserving
        input order in the returned ids. An empty ``flights`` sequence inserts
        nothing and returns ``[]``.
        """
        ids: list[int] = []
        for flight_item in flights:
            row = flight_to_silver_row(
                flight_item, execution_id=execution_id, captured_at=captured_at
            )
            result = self._conn.execute(flight.insert().values(**row))
            ids.append(result.inserted_primary_key[0])
        return ids


class GoldRepository:
    """Reader/writer of alert history in ``gold.flight_alert``.

    Produces the ``last_alerted_prices`` mapping consumed by
    ``domain.deduplication.select_flights_to_notify``.
    """

    def __init__(self, connection: Connection) -> None:
        self._conn = connection

    def record_alerts(
        self, *, execution_id: UUID, alerts: Sequence[Alert]
    ) -> list[int]:
        """Append the alerts effectively sent this run; return generated ``id`` values.

        Contract: one append-only row per :class:`Alert` via
        :func:`alert_to_gold_row`, preserving input order in the returned ids.
        These are the flights that passed deduplication. Empty input -> ``[]``.
        Never updates/deletes prior rows (append-only history, architecture.md §3).
        """
        ids: list[int] = []
        for alert in alerts:
            row = alert_to_gold_row(alert, execution_id=execution_id)
            result = self._conn.execute(flight_alert.insert().values(**row))
            ids.append(result.inserted_primary_key[0])
        return ids

    def last_alerted_prices(self, route: Route) -> dict[str, Decimal]:
        """Return ``{flight_id: last alerted price}`` for the given route.

        Contract: for every ``flight_id`` belonging to ``route`` that has at least
        one alert in ``gold.flight_alert``, map it to the ``price`` of its most
        recent alert (max ``alerted_at``). Prices are :class:`Decimal`. A flight
        never alerted is simply absent from the mapping (the dedup rule treats
        absence as "first occurrence"). This is exactly the ``Mapping`` expected
        by ``domain.deduplication.select_flights_to_notify``.

        "Belonging to ``route``" is decided by the route component of the
        ``flight_id`` (``{origin}-{destination}-{YYYY-MM-DD}-...``), so the query
        can filter on that prefix.
        """
        prefix = (
            f"{route.origin}-{route.destination}-{route.departure_date.isoformat()}-"
        )

        latest = (
            select(
                flight_alert.c.flight_id,
                sqlalchemy_func.max(flight_alert.c.alerted_at).label("max_alerted_at"),
            )
            .where(flight_alert.c.flight_id.like(f"{prefix}%"))
            .group_by(flight_alert.c.flight_id)
            .subquery()
        )

        stmt = select(flight_alert.c.flight_id, flight_alert.c.price).join(
            latest,
            (flight_alert.c.flight_id == latest.c.flight_id)
            & (flight_alert.c.alerted_at == latest.c.max_alerted_at),
        )

        result = self._conn.execute(stmt)
        return {row.flight_id: row.price for row in result}
